---
- name: Include OS Specific Variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install MIT KDC packages
  package:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ kdc_packages }}"

- name: Set krb5.conf
  template: src=krb5.conf.j2 dest=/etc/krb5.conf backup=yes

- name: Set kdc.conf
  template: src=kdc.conf.j2 dest=/etc/krb5kdc/kdc.conf backup=yes

- name: Set kadm5.acl
  template: src=kadm5.acl.j2 dest=/etc/krb5kdc/kadm5.acl backup=yes

- name: Create KDC database
  command: /usr/sbin/kdb5_util create -s -P {{ krb5_kdc_master_passwd }} creates=/etc/krb5kdc/principal


- name: Start Kerberos
  service: name={{ item }} state=restarted enabled=yes
  with_items: "{{ restart_kdc_packages }}"

- name: Create Cloudera Manager admin princ
  command: /usr/sbin/kadmin.local -q "addprinc -pw {{ krb5_kdc_admin_passwd }} {{ krb5_kdc_admin_user }}"
