---
- name: Stop Ambari Server
  service: name=ambari-server state=stopped

- name: Reload Ambari-Server
  service: name=ambari-server state=restarted enabled=yes
  notify: "Wait for Ambari Server to start listening on port 8080"

- name: Wait for Ambari Server to start listening on port 8080
  wait_for:
    port: 8080
    host: 0.0.0.0
    delay: 1
