---
- name: Add OS specific Variables
  include_vars: "{{ ansible_os_family }}.yml"
- name: Add Databases Variables
  include_vars: database.yml

- name: Install the mysql packages in Debian derivatives
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ mysql_pkgs }}"

- name: Change the Bind Address
  lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp=^bind-address line=bind-address={{ ansible_fqdn }}
  when: (ansible_distribution|lower == "ubuntu")

- name: Change the Bind Address
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line=bind-address={{ ansible_fqdn }}
  when: (ansible_distribution|lower == "debian") 

- name: Start the mysql services
  service: name={{ mysql_service }} state=restarted enabled=yes

- name: Include Task Creating Password Secure Installation
  include_tasks: mysql_secure_installation.yml

- name: Include Task for Creating Databases
  include_tasks: databases.yml
