---

- name: Set root password
  command: 'mysql -uroot -ne "{{ item }}"'
  with_items:
    - SET PASSWORD FOR 'root'@'localhost'  = PASSWORD('{{ mysql_root_password }}')

- name: Remove anonymous users
  command: 'mysql -uroot -p{{ mysql_root_password }} -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''

- name: Disable remote login for root
  command: 'mysql -uroot -p{{ mysql_root_password }} -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('127.0.0.1', '::1', 'localhost')

- name: Remove the test database
  mysql_db: login_user=root login_password={{ mysql_root_password }} db=test state=absent

- name: Reload privilege tables
  command: 'mysql -uroot -p{{ mysql_root_password }} -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
